# Generated by Django 2.2.12 on 2022-01-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='positive',
            name='laboratory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='positive',
            name='variant_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
