# Generated by Django 2.2.12 on 2022-01-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20220104_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positive',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='isolation',
            name='positivity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isolation', to='record.Positive'),
        ),
    ]
