# Generated by Django 2.2.12 on 2022-01-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20220113_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='high_insulation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
