# Generated by Django 2.2.12 on 2022-01-11 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'There is already a user with this email.'}, max_length=254, unique=True, verbose_name='email addres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='You must enter a number with the following format: 3837430000. Up to 10 digits.', regex='\\d{10,10}$')]),
        ),
    ]
